### ISSUE TITLE
Unificar el lenguaje de las pruebas

### ISSUE THREAD

**Issue by evolentini** [nicolascecchi/tp3-testing-bdd#1]
Gerkin se encuentra traducido a más de 70 lenguajes para que se pueda utilizar en el lenguaje natural del cliente. Si las pruebas se vana escribir en ingles, entonces todo el archivo de features debe escribirse en ese idioma, de lo contrario todo debe estar en castellano.

**Comment by nicolascecchi** [comment]
Se traducen las features.
