### ISSUE TITLE
No se puede actualizar la clave de una lista vacía

### ISSUE THREAD

**Issue by evolentini** [nicolascecchi/tp3-testing-bdd#2]
Esta prueba tiene problemas conceptuales (no se puede actualizar una clave en una lista vacía) y problemas de ejecución: el código de cada escenario se ejecuta en forma independiente, es decir que la clave agregada en el escenario `Agregar un elemento a una lista vacía` no está disponible en los otros escenarios. Esta prueba no tiene errores de ejecución solamente porque para agregar y para actualizar se utiliza la misma función.

https://github.com/nicolascecchi/tp3-testing-bdd/blob/e27a67695c3747e3d7c6b8e075eab0b1eb70d160/features/listas_vacias.feature#L4-L7

https://github.com/nicolascecchi/tp3-testing-bdd/blob/e27a67695c3747e3d7c6b8e075eab0b1eb70d160/features/listas_vacias.feature#L18-L20

**Comment by nicolascecchi** [comment]
Se llevó la prueba a las features de "listas_con_elementos" bajo la condición de "Dado una lista con al menos un elemento".
