### ISSUE TITLE
Se deben mejorar notablemente algunas pruebas

### ISSUE THREAD

**Issue by evolentini** [nicolascecchi/tp3-testing-bdd#3]
La idea de los escenarios es que derriban claramente el comportamiento esperado del desarrollo. En esta prueba por ejemplo

https://github.com/nicolascecchi/tp3-testing-bdd/blob/e27a67695c3747e3d7c6b8e075eab0b1eb70d160/features/listas_con_elementos.feature#L10-L17

No se entiende que es lo que estas haciendo. Una forma mucho más clara de plantear la misma prueba sería:

```Gherkin
Scenario Outline: Contar elementos de un diccionario no vacio
  When agrego los <elementos> a un diccionario 
  Then el diccionario tiene almacenado <cantidad> elementos
  Examples:    
    | elementos                             | cantidad |
    | [("Uno",1)]                           |     2    | 
    | [("Uno",1)("Tres",3)]                 |     3    | 
    | [("Uno",1),("Dos",2),("Tres",3)]      |     4    | 
```

**Comment by nicolascecchi** [comment]
Se mejora la prueba siguiendo las recomendacones indicadas.
