### ISSUE TITLE
Se debe corregir el antecedente del archivo feature

### ISSUE THREAD

**Issue by evolentini** [nicolascecchi/tp3-testing-bdd#4]
El anteccedente:

https://github.com/nicolascecchi/tp3-testing-bdd/blob/e27a67695c3747e3d7c6b8e075eab0b1eb70d160/features/listas_con_elementos.feature#L3-L4

está mal escrito porque en realidad para que los escenarios funcionen correctamente hace falta que haya exactamente un elemento en la lista, y ademas con una clave y valores determinados. Una forma mucho más clara de escribirlo sería

```Gherkin
Background: Pruebas sobre diccionarios con elementos
  Given una lista que contiene solo una clave "{clave}" con el valor "{valor}" 
```
o bien si queres reutilizar los pasos de la otra funcionalidad

```Gherkin
Background: Pruebas sobre diccionarios con elementos
  Given una lista vacia
  When agrego la clave "{clave}" con el valor "{valor}"
```

**Comment by nicolascecchi** [comment]
Se modificó el escenario de acuerdo a las recomendaciones indicadas.
